name: strapi-test
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  setup:
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      - uses: actions/checkout@v3
      - run: make setup
  test:
    needs: setup
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      - run: make test
  lint:
    runs-on: ubuntu-latest
    steps: # список шагов, которые надо выполнить
      - uses: actions/checkout@v3
      - run: make lint
